# docker/docker-compose.dev.yml
version: '3.8'

services:
  # 开发环境 MySQL
  mysql-dev:
    image: mysql:8.0
    container_name: cyber-chess-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cyber_chess_dev
      MYSQL_USER: developer
      MYSQL_PASSWORD: dev123456
    ports:
      - "3307:3306"  # 使用不同端口避免冲突
    volumes:
      - mysql_dev_data:/var/lib/mysql

  # phpMyAdmin 用于数据库管理
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: cyber-chess-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-dev
      PMA_USER: developer
      PMA_PASSWORD: dev123456
    depends_on:
      - mysql-dev

volumes:
  mysql_dev_data: