# docker/docker-compose.dev.yml
version: '3.8'

services:
  # Development PostgreSQL
  postgres-dev:
    image: postgres:15-alpine
    container_name: cyber-chess-db-dev
    environment:
      POSTGRES_DB: cyber_chess_dev
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  # Development Redis
  redis-dev:
    image: redis:7-alpine
    container_name: cyber-chess-redis-dev
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data

  # Development MinIO
  minio-dev:
    image: minio/minio:latest
    container_name: cyber-chess-minio-dev
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: developer
      MINIO_ROOT_PASSWORD: dev123456
    ports:
      - "9002:9000"
      - "9003:9001"
    volumes:
      - minio_dev_data:/data

  # Adminer for database management
  adminer:
    image: adminer
    container_name: cyber-chess-adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres-dev
    depends_on:
      - postgres-dev

volumes:
  postgres_dev_data:
  redis_dev_data:
  minio_dev_data: